project:
  type: website

website:
  title: "AI/ML Notes"
  description: "One of the beautiful things about Machine Learning is you are not going to remember lot of details if you are not practicing it."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true

execute:
  freeze: auto